name: Markdown QA
on: [push,pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Markdown files
        run: |
          find . -name "*.md" | sort
